apiVersion: v1
kind: Service
metadata:
  name: dksinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http
      port: 9897
      protocol: TCP
      targetPort: http
    - port: 9990
      targetPort: grpc
      protocol: TCP
      name: grpc
